### ISSUE TITLE
Add coveralls to build process

### ISSUE THREAD

**Issue by inirudebwoy** [inirudebwoy/interview-task#2]
I have opened issue with coveralls https://github.com/lemurheavy/coveralls-public/issues/568

Under repo management in coveralls.io there is only Master branch.
Opened this issue for tracking upstream.

**Comment by netmask** [comment]
Same here . also im seeing duplicated repos

**Comment by inirudebwoy** [comment]
I think you wanted to comment on the real issue :)

**Comment by inirudebwoy** [comment]
Coverage is tracked now.
